### ISSUE TITLE
Gratuitous stratum compatibility breaks

### ISSUE THREAD

**Issue by luke-jr** [slushpool/poclbm-zcash#1]
I stumbled across https://github.com/slushpool/poclbm-zcash/wiki/Stratum-protocol-changes-for-ZCash

Is this spec final? Or still open to review?

Why break compatibility unnecessarily?

Eg, use:

```
{"id": 1, "method": "mining.subscribe", "params": ["MINER_USER_AGENT", "SESSION_ID", "CONNECT_HOST", CONNECT_PORT]}\n
{"id": 1, "result": [[], "NONCE_1/SESSION_ID", extranonce2_size], "error": null}\n

{"id": null, "method": "mining.notify", "params": ["JOB_ID", "PREVHASH", "MERKLEROOT", "RESERVED/IGNORED", [], "VERSION", "BITS", "TIME", CLEAN_JOBS]}\n

{"id": 4, "method": "mining.submit", "params": ["WORKER_NAME", "JOB_ID", "NONCE_2", "TIME", "EQUIHASH_SOLUTION"]}\n
```

**Comment by janbraiins** [comment]
Hi Luke,
this is still currently work in progress, the spec is not final yet.

**Comment by luke-jr** [comment]
I was pondering possibly someday supporting Equihash in BFGMiner, and so it would be nice if the stratum code paths could be mostly the same. :)

(but I do like set_target replacing set_difficulty... that's worth it)

**Comment by slush0** [comment]
We actually had long long discussions with Zcash developers and those changes make sense. We tried to make pretty minimal changes, still we couldn't resist to add tiny improvements like CONNECT_HOST and CONNECT_PORT. I don't think it will require deep changes in miners anyway. I was able to fix poclbm to Zcash protocol in matter of two hours.

Also the main discussion is actually here: https://github.com/zcash/zips/pull/78. Wiki notes in this repository were just my initial writedown.

**Comment by luke-jr** [comment]
How can I know whether to send CONNECT_HOST/PORT without knowing in advance the algorithm being used?

**Comment by ucwong** [comment]
...I want to know  if there are any pools can be matched , when the protocol has been changed by the miner?

**Comment by janbraiins** [comment]
Hi, it's still work in progress, I suggest you follow comments in the official ZIP: https://github.com/zcash/zips/pull/78
