### ISSUE TITLE
zcash stratum docs wrong about subscribe response

### ISSUE THREAD

**Issue by aleqx** [slushpool/poclbm-zcash#3]
https://github.com/slushpool/poclbm-zcash/wiki/Stratum-protocol-changes-for-ZCash

`{"id": 1, "result": ["NONCE_1", "SESSION_ID"], "error": null}\n`

should be

`{"id": 1, "result": ["SESSION_ID", "NONCE_1"], "error": null}\n`

**Comment by ondrejsika** [comment]
Fixed, thanks @aleqx !
